AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'POST,GET,DELETE'"
      AllowOrigin: "'*'"

Resources:
  TodoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: todo/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies: AmazonDynamoDBFullAccess
      Events:
        Todos:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /todos
            Method: get
        AddTodos:
          Type: Api
          Properties:
            Path: /todos
            Method: post
        Options:
          Type: Api
          Properties:
            Path: /todos
            Method: options
        DeleteTodos:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: DELETE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TodoApi:
    Description: 'API Gateway endpoint URL for Prod stage for Todo function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos/'
  TodoFunction:
    Description: 'Todo Lambda Function ARN'
    Value: !GetAtt TodoFunction.Arn
  TodoFunctionIamRole:
    Description: 'Implicit IAM Role created for Todo function'
    Value: !GetAtt TodoFunctionRole.Arn
